version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: smartstore-api-gateway:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=smartstore-jwt-secret-2024
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartstore-network

  # User Service
  user-service:
    image: smartstore-user-service:latest
    environment:
      - NODE_ENV=production
      - JWT_SECRET=smartstore-jwt-secret-2024
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartstore-network

  # Product Service
  product-service:
    image: smartstore-product-service:latest
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartstore-network

  # Order Service
  order-service:
    image: smartstore-order-service:latest
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartstore-network

  # Payment Service
  payment-service:
    image: smartstore-payment-service:latest
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartstore-network

  # Inventory Service
  inventory-service:
    image: smartstore-inventory-service:latest
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - smartstore-network

  # Notification Service
  notification-service:
    image: smartstore-notification-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # Analytics Service
  analytics-service:
    image: smartstore-analytics-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # AI/ML Service
  ai-ml-service:
    image: smartstore-ai-ml-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # Search Service
  search-service:
    image: smartstore-search-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # File Service
  file-service:
    image: smartstore-file-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # Blockchain Service
  blockchain-service:
    image: smartstore-blockchain-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # IoT Service
  iot-service:
    image: smartstore-iot-service:latest
    environment:
      - NODE_ENV=production
    networks:
      - smartstore-network

  # Redis (reuse existing)
  redis:
    image: redis:7.2-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - smartstore-network

networks:
  smartstore-network:
    external: true

volumes:
  redis_data: 